CREATE TABLE IF NOT EXISTS `absensi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `karyawan_id` INT UNSIGNED NOT NULL,
  `tanggal` DATE NOT NULL,
  `waktu_masuk` TIME DEFAULT NULL,
  `waktu_pulang` TIME DEFAULT NULL,
  `lokasi_masuk` VARCHAR(255) DEFAULT NULL,
  `lokasi_pulang` VARCHAR(255) DEFAULT NULL,
  `latitude_masuk` DECIMAL(10, 8) DEFAULT NULL,
  `longitude_masuk` DECIMAL(11, 8) DEFAULT NULL,
  `latitude_pulang` DECIMAL(10, 8) DEFAULT NULL,
  `longitude_pulang` DECIMAL(11, 8) DEFAULT NULL,
  `status` ENUM('Hadir','Terlambat','Izin','Sakit','Alpha','Cuti') NOT NULL DEFAULT 'Hadir',
  `jam_kerja` DECIMAL(5, 2) DEFAULT 0,
  `jam_lembur` DECIMAL(5, 2) DEFAULT 0,
  `terlambat` INT DEFAULT 0 COMMENT 'Keterlambatan dalam menit',
  `keterangan` TEXT DEFAULT NULL,
  `device_masuk` VARCHAR(255) DEFAULT NULL,
  `device_pulang` VARCHAR(255) DEFAULT NULL,
  `shift` ENUM('pagi','siang','sore','malam') DEFAULT 'siang',
  `jam_shift_mulai` TIME DEFAULT NULL,
  `jam_shift_selesai` TIME DEFAULT NULL,
  `location_metadata_masuk` TEXT DEFAULT NULL,
  `location_metadata_pulang` TEXT DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `updated_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_absensi_karyawan_tanggal` (`karyawan_id`, `tanggal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
