-- app/Database/sql_manual/aset_tetap.sql

CREATE TABLE IF NOT EXISTS `aset_tetap_kategori` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_kategori` VARCHAR(50) NOT NULL,
  `nama_kategori` VARCHAR(100) NOT NULL,
  `masa_manfaat` INT DEFAULT 4,
  `masa_manfaat_bulan` INT DEFAULT 48,
  `metode_penyusutan` ENUM('Garis Lurus','Saldo Menurun') DEFAULT 'Garis Lurus',
  `tarif_penyusutan` DECIMAL(5,2) DEFAULT 0.00,
  `coa_id_aset` INT DEFAULT NULL,
  `coa_id_akumulasi` INT DEFAULT NULL,
  `coa_id_beban` INT DEFAULT NULL,
  `keterangan` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `aset_tetap` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_aset` VARCHAR(50) NOT NULL,
  `nama_aset` VARCHAR(150) NOT NULL,
  `kategori_id` INT DEFAULT NULL,
  `tanggal_perolehan` DATE DEFAULT NULL,
  `harga_perolehan` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_sisa` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_residu` DECIMAL(15,2) DEFAULT 0.00,
  `masa_manfaat_tahun` INT DEFAULT 4,
  `masa_manfaat_bulan` INT DEFAULT 48,
  `metode_penyusutan` ENUM('Garis Lurus','Saldo Menurun','Tidak Disusutkan') DEFAULT 'Garis Lurus',
  `penyusutan_per_bulan` DECIMAL(15,2) DEFAULT 0.00,
  `akumulasi_penyusutan` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_buku` DECIMAL(15,2) DEFAULT 0.00,
  `status` ENUM('Aktif','Disusutkan Penuh','Dilepas','Rusak','Dijual') DEFAULT 'Aktif',
  `kondisi` VARCHAR(50) DEFAULT 'Baik',
  `lokasi` VARCHAR(150) DEFAULT NULL,
  `departemen` VARCHAR(100) DEFAULT NULL,
  `penanggung_jawab` VARCHAR(150) DEFAULT NULL,
  `penanggung_jawab_id` INT DEFAULT NULL,
  `coa_aset_id` INT DEFAULT NULL,
  `coa_akumulasi_id` INT DEFAULT NULL,
  `coa_beban_id` INT DEFAULT NULL,
  `coa_id_aset` INT DEFAULT NULL,
  `coa_id_akumulasi` INT DEFAULT NULL,
  `coa_id_beban` INT DEFAULT NULL,
  `merk` VARCHAR(100) DEFAULT NULL,
  `model` VARCHAR(100) DEFAULT NULL,
  `serial_number` VARCHAR(100) DEFAULT NULL,
  `keterangan` TEXT DEFAULT NULL,
  `foto` VARCHAR(255) DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `penyusutan` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_penyusutan` VARCHAR(50) DEFAULT NULL,
  `periode` DATE DEFAULT NULL,
  `periode_bulan` INT DEFAULT NULL,
  `periode_tahun` INT DEFAULT NULL,
  `tanggal_penyusutan` DATE DEFAULT NULL,
  `aset_id` INT DEFAULT NULL,
  `nilai_buku_awal` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_penyusutan` DECIMAL(15,2) DEFAULT 0.00,
  `nominal` DECIMAL(15,2) DEFAULT 0.00,
  `akumulasi_penyusutan` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_buku_akhir` DECIMAL(15,2) DEFAULT 0.00,
  `jurnal_id` INT DEFAULT NULL,
  `status` ENUM('Draft','Posted','Dibatalkan') DEFAULT 'Draft',
  `keterangan` TEXT DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `penyusutan_aset` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_penyusutan` VARCHAR(50) DEFAULT NULL,
  `periode` DATE DEFAULT NULL,
  `periode_bulan` INT DEFAULT NULL,
  `periode_tahun` INT DEFAULT NULL,
  `tanggal_penyusutan` DATE DEFAULT NULL,
  `aset_id` INT DEFAULT NULL,
  `nilai_buku_awal` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_penyusutan` DECIMAL(15,2) DEFAULT 0.00,
  `nominal` DECIMAL(15,2) DEFAULT 0.00,
  `akumulasi_penyusutan` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_buku_akhir` DECIMAL(15,2) DEFAULT 0.00,
  `jurnal_id` INT DEFAULT NULL,
  `status` ENUM('Draft','Posted','Dibatalkan') DEFAULT 'Draft',
  `keterangan` TEXT DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pelepasan_aset` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_pelepasan` VARCHAR(50) NOT NULL,
  `tanggal_pelepasan` DATE DEFAULT NULL,
  `aset_id` INT NOT NULL,
  `jenis_pelepasan` ENUM('Penjualan','Hibah','Pemusnahan/Rusak','Lainnya','Dijual','Dihibahkan','Dimusnahkan') DEFAULT 'Penjualan',
  `pembeli_penerima` VARCHAR(150) DEFAULT NULL,
  `harga_jual` DECIMAL(15,2) DEFAULT 0.00,
  `nilai_buku_saat_pelepasan` DECIMAL(15,2) DEFAULT 0.00,
  `laba_rugi` DECIMAL(15,2) DEFAULT 0.00,
  `laba_rugi_pelepasan` DECIMAL(15,2) DEFAULT 0.00,
  `coa_id_kas_bank` INT DEFAULT NULL,
  `coa_id_laba_rugi` INT DEFAULT NULL,
  `jurnal_id` INT DEFAULT NULL,
  `status` ENUM('Draft','Approved','Posted','Dibatalkan','Disetujui','Selesai') DEFAULT 'Draft',
  `disetujui_oleh` INT DEFAULT NULL,
  `disetujui_at` DATETIME DEFAULT NULL,
  `keterangan` TEXT DEFAULT NULL,
  `lampiran` VARCHAR(255) DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
