-- app/Database/sql_manual/kas_bank.sql

CREATE TABLE IF NOT EXISTS `rekonsiliasi` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `periode` DATE NOT NULL,
  `coa_bank_id` INT NOT NULL,
  `nomor_rekening_bank` VARCHAR(50) DEFAULT NULL,
  `nama_bank` VARCHAR(100) DEFAULT NULL,
  `saldo_awal_bank` DECIMAL(15,2) DEFAULT 0.00,
  `saldo_akhir_bank` DECIMAL(15,2) DEFAULT 0.00,
  `saldo_awal_buku` DECIMAL(15,2) DEFAULT 0.00,
  `saldo_akhir_buku` DECIMAL(15,2) DEFAULT 0.00,
  `tanggal_rekonsiliasi` DATE DEFAULT NULL,
  `data_setoran_dalam_perjalanan` TEXT DEFAULT NULL,
  `data_cek_dalam_edar` TEXT DEFAULT NULL,
  `data_penyesuaian_bank` TEXT DEFAULT NULL,
  `data_penyesuaian_buku` TEXT DEFAULT NULL,
  `total_setoran_dalam_perjalanan` DECIMAL(15,2) DEFAULT 0.00,
  `total_cek_dalam_edar` DECIMAL(15,2) DEFAULT 0.00,
  `total_penyesuaian_bank` DECIMAL(15,2) DEFAULT 0.00,
  `total_penyesuaian_buku` DECIMAL(15,2) DEFAULT 0.00,
  `keterangan` TEXT DEFAULT NULL,
  `lampiran_rekening_koran` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('Draft','Selesai','Dibatalkan') DEFAULT 'Draft',
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kas_kecil` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tanggal` DATE NOT NULL,
  `kode_transaksi` VARCHAR(50) NOT NULL,
  `tipe` ENUM('Pemasukan','Pengeluaran') NOT NULL,
  `jumlah` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `keterangan` TEXT DEFAULT NULL,
  `coa_lawan_id` INT DEFAULT NULL,
  `coa_lawan_kode` VARCHAR(50) DEFAULT NULL,
  `coa_lawan_nama` VARCHAR(150) DEFAULT NULL,
  `karyawan_id` INT DEFAULT NULL,
  `nama_karyawan` VARCHAR(150) DEFAULT NULL,
  `spk_id` INT DEFAULT NULL,
  `nomor_spk` VARCHAR(50) DEFAULT NULL,
  `no_bukti` VARCHAR(100) DEFAULT NULL,
  `lampiran` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('Draft','Posted','Dibatalkan') DEFAULT 'Draft',
  `posted_at` DATETIME DEFAULT NULL,
  `jurnal_id` INT DEFAULT NULL,
  `nomor_jurnal` VARCHAR(50) DEFAULT NULL,
  `metode_imprest` TINYINT(1) DEFAULT 0,
  `saldo_setelah` DECIMAL(15,2) DEFAULT 0.00,
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pengeluaran_pribadi` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tanggal` DATE NOT NULL,
  `kode_pengeluaran` VARCHAR(50) NOT NULL,
  `karyawan_id` INT DEFAULT NULL,
  `nama_karyawan` VARCHAR(150) DEFAULT NULL,
  `jenis` VARCHAR(100) DEFAULT NULL,
  `jumlah` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `keterangan` TEXT DEFAULT NULL,
  `tujuan_penggunaan` TEXT DEFAULT NULL,
  `coa_id_debit` INT DEFAULT NULL,
  `coa_debit_kode` VARCHAR(50) DEFAULT NULL,
  `coa_debit_nama` VARCHAR(150) DEFAULT NULL,
  `coa_id_kredit` INT DEFAULT NULL,
  `coa_kredit_kode` VARCHAR(50) DEFAULT NULL,
  `coa_kredit_nama` VARCHAR(150) DEFAULT NULL,
  `spk_id` INT DEFAULT NULL,
  `nomor_spk` VARCHAR(50) DEFAULT NULL,
  `no_bukti` VARCHAR(100) DEFAULT NULL,
  `lampiran` VARCHAR(255) DEFAULT NULL,
  `status_hutang` VARCHAR(50) DEFAULT 'Belum Lunas',
  `tanggal_jatuh_tempo` DATE DEFAULT NULL,
  `tanggal_pelunasan` DATE DEFAULT NULL,
  `mutasi_bank_id` INT DEFAULT NULL,
  `kas_kecil_id` INT DEFAULT NULL,
  `jumlah_dibayar` DECIMAL(15,2) DEFAULT 0.00,
  `status` ENUM('Draft','Posted','Dibatalkan') DEFAULT 'Draft',
  `posted_at` DATETIME DEFAULT NULL,
  `jurnal_id` INT DEFAULT NULL,
  `jurnal_pelunasan_id` INT DEFAULT NULL,
  `nomor_jurnal` VARCHAR(50) DEFAULT NULL,
  `catatan_internal` TEXT DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
